# hub_link config for connecting to NervesCloud using Shared Secret auth.
#
# Get your key and secret from the NervesCloud dashboard under
# your product's device authentication settings.

host = "devices.nervescloud.com"

# Device serial number - set directly or via a command.
serial_number = "my-devicez-455"
# serial_number_command = "cat /sys/firmware/devicetree/base/serial-number"

# Block device that fwup writes firmware to.
# fwup_devpath = "/dev/mmcblk0"
# fwup_task = "upgrade"

[auth]
type = "shared_secret"
key = "nhp_gsd0MkL+ybJ1aEYYyopTc5q7kbtha9/vaPWCe2l5SI0"
secret = "2HiToFAWn4Cpprho1SrK94mN7c4XC5D5FUnUOeTmcSE"

[firmware]
uuid = "00000000-0000-0000-0000-000000000000"
version = "0.0.0"
platform = "rpi4"
architecture = "arm"
product = "my-product"
